name: Deploy Backend to Heroku

on:
  workflow_run:
    workflows: ["ci_pipeline"]
    types:
      - completed
      - success

jobs:
  initial:
    runs-on: ubuntu-latest
    steps:
      - name: Dummy Step
        run: echo "Ready to deploy backend"

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          path: 'server'

      - name: Install dependencies
        run: 
          npm install

      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.13.15 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "minuet" #Must be unique in Heroku
          heroku_email: "jakob.reinwald@yahoo.com"
      

      # - name: Login to Heroku
      #   run: npx heroku login -i
      #   env:
      #     HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      #     heroku_app_name: "minuet"
      #     heroku_email: "jakob.reinwald@yahoo.com"

      # - name: Add Heroku remote
      #   run: git remote add heroku https://git.heroku.com/minuet.git  # App git location

      # - name: Deploy to Heroku
      #   run: npx heroku git:remote -a minuet

      # - name: Deploy to Heroku
      #   run: git push heroku main
