name: Deploy Backend to Heroku

on:
  workflow_run:
    workflows: ["ci_pipeline"]
    types:
      - completed
      - success

jobs:
  initial:
    runs-on: ubuntu-latest
    steps:
      - name: Dummy Step
        run: echo "Ready to deploy backend"

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Navigate to server and install
        run: |
          cd server
          npm install

      - name: Login to Heroku
        run: npx heroku login -i
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

      - name: Add Heroku remote
        run: git remote add heroku https://git.heroku.com/minuet.git  # App git location

      - name: Deploy to Heroku
        run: npx heroku git:remote -a minuet

      - name: Deploy to Heroku
        run: git push heroku main
