# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: ci_pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'

    - name: Install dependencies (frontend)
      working-directory: ./minuet 
      run: npm install

    - name: Build frontend
      working-directory: ./minuet
      run: npm run build  # Adjust command based on your build script

    - name: Install dependencies (backend)
      working-directory: ./server 
      run: npm install

    - name: Run tests (backend)
      working-directory: ./server
      run: npm test  
