# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: ci_pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js for server
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
        cache-dependency-path: ./server/package-lock.json

    - name: Install dependencies (backend)
      working-directory: ./server 
      run: npm install

    - name: Run tests (backend)
      working-directory: ./server
      run: |          
        touch .env.local
        echo MONGO_USERNAME=${{ secrets.MONGO_USERNAME }} >> .env.local
        echo MONGO_PASSWORD=${{ secrets.MONGO_PASSWORD }} >> .env.local
        echo MONGO_CLUSTER=${{ secrets.MONGO_CLUSTER }} >> .env.local
        echo MONGO_HOST=${{ secrets.MONGO_HOST }} >> .env.local
        echo SPOTIFY_CLIENT_ID=${{ secrets.SPOTIFY_CLIENT_ID }} >> .env.local
        echo SPOTIFY_CLIENT_SECRET=${{ secrets.SPOTIFY_CLIENT_SECRET }} >> .env.local
        npm test

    - name: Setup Node.js for frontend
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
        cache-dependency-path: ./minuet/package-lock.json
        
    - name: Install dependencies (frontend)
      working-directory: ./minuet 
      run: npm install

    - name: Run tests (frontend)
      working-directory: ./minuet 
      run: |          
        touch .env
        echo REACT_APP_SPOTIFY_CLIENT_ID=${{ secrets.REACT_APP_SPOTIFY_CLIENT_ID }} >> .env
        echo REACT_APP_BACKEND_URL=${{ secrets.REACT_APP_BACKEND_URL }} >> .env
        echo REACT_APP_FRONTEND_URL=${{ secrets.REACT_APP_FRONTEND_URL }} >> .env
        npm test

    - name: Build frontend
      working-directory: ./minuet
      run: CI=false npm run build  # Adjust command based on your build script
