name: Deploy Frontend to GitHub Pages

on:
  workflow_run:
    workflows: ["ci_pipeline"]
    types:
      - completed

jobs:
  initial:
    runs-on: ubuntu-latest
    steps:
      - name: Dummy Step
        run: echo "Ready to build and deploy frontend"
        
  deploy:
    runs-on: ubuntu-latest
    needs: ci_pipeline

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build and Deploy Frontend
        run: |
          cd minuet  # Navigate to your frontend directory
          touch .env
          echo REACT_APP_SPOTIFY_CLIENT_ID=${{ secrets.REACT_APP_SPOTIFY_CLIENT_ID }} >> .env
          echo REACT_APP_BACKEND_URL=${{ secrets.REACT_APP_BACKEND_URL }} >> .env
          echo REACT_APP_FRONTEND_URL=${{ secrets.REACT_APP_FRONTEND_URL }} >> .env
          npm install  # Install dependencies (if needed)
          CI=false npm run build  # Build your frontend
          echo "www.minuet.lol" > build/CNAME # Add custom domain
          mv build ../public  # Move build files to temporary directory

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_PAGES_ACCESS }}
          publish_dir: ./public
