name: Deploy Frontend to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build and Deploy Frontend
        run: |
          cd minuet  # Navigate to your frontend directory
          npm install  # Install dependencies (if needed)
          CI=false npm run build  # Build your frontend
          mv build ../public  # Move build files to temporary directory

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_PAGES_ACCESS }}
          publish_dir: ./public
